name: Upload Python Package to PyPI

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  deploy_docs:
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Necessary to push new branches and commit files
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install -U sphinx
          python -m pip install sphinx_autodoc_typehints
          python -m pip install sphinx-rtd-theme
          python -m pip install -r requirements.txt
      - name: Build Documentation
        run: |
          cd docs
          make html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          publish_branch: gh-pages
      - name: git actions
        run: |
          git checkout main
          # Make your changes and push them to the remote repository
          git add .
          git commit -m "Update documentation"
          git push origin main

          # Checkout the gh-pages branch
          git checkout gh-pages

          # Merge the main branch into the gh-pages branch
          git merge main

          # Push the gh-pages branch to the remote repository
          git push origin gh-pages 
  build:
    name: Build and upload package to PyPI
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x  # Replace with your desired Python version

    # Step 3: Install dependencies required for packaging
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    # Step 4: Build the package
    - name: Build the package
      run: python -m build

    # Step 5: Upload the package to PyPI
    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # PyPI API token stored as a secret in GitHub
      run: |
        python -m twine upload dist/*

    # Optional Step: Clean up build artifacts
    - name: Clean up
      run: rm -rf dist
